version: '3.8'
services:
  node:
    image: node:16.14.0
    working_dir: /app
    volumes:
      - ".:/app"
    ports:
      - "8080:8080"
    links:
      - db
      - mailhog
    command: [ "npm", "run", "dev" ]
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
      - MAIL_HOST=mailhog
      - MAIL_FROM=from@me.com

  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  mailhog:
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - 1025:1025
      - 8025:8025
volumes:
  db:
    driver: local